{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.proxy }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.cm" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  STARHUB_SERVER_SPACE_SESSION_SECRET_KEY: {{ sha256sum .Release.Name | trunc 32 | quote }} # c8f771f2a178089b99172cbbd7e3b01d
  STARHUB_DATABASE_TIMEZONE: {{ include "postgresql.timezone" . | quote }}
  STARHUB_SERVER_GITSERVER_HOST: {{ include "gitea.endpoint" . | quote }}
  STARHUB_SERVER_GITSERVER_URL: {{ include "gitea.url.root" . | quote }}
  STARHUB_SERVER_GITSERVER_WEBHOOK_URL: {{ include "server.url.callback.git" . | quote }}
  STARHUB_SERVER_INTERNAL_ROOT_DOMAIN: {{ include "builder.full.internal.domain" . | quote }}
  STARHUB_SERVER_SAAS: "false"
  STARHUB_SERVER_MIRRORSERVER_ENABLE: "false"
  STARHUB_SERVER_MIRRORSERVER_TYPE: "gitea"
  STARHUB_JWT_SIGNING_KEY: "e2kk6awudc3620ed9a"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.cm.nginx" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- range .Values.global.builder.internal }}
  {{ .domain }}.conf: |
    server {
        listen 80;
        server_name {{ printf "*.%s.%s" (include "runner.namespace" $) .domain }};

        location / {
            proxy_http_version 1.1;
            proxy_pass http://{{ .service.host }}:{{ .service.port }};
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
       }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root  /usr/share/nginx/html;
        }
    }
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
  {{- end }}