{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.casdoor }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.cm" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  app.conf: |
    appname = casdoor
    httpport = 8000
    runmode = prod
    copyrequestbody = true
    driverName = postgres
    dataSourceName = {{ include "casdoor.postgresql.datasource" . | quote }}
    dbName =
    tableNamePrefix =
    showSql = false
    redisEndpoint =
    defaultStorageProvider =
    isCloudIntranet = false
    authState = "casdoor"
    socks5Proxy = "127.0.0.1:10808"
    verificationCodeTimeout = 10
    initScore = 0
    logPostOnly = true
    origin =
    originFrontend =
    staticBaseUrl = "https://cdn.casbin.org"
    isDemoMode = false
    batchSize = 100
    enableGzip = true
    ldapServerPort = 389
    radiusServerPort = 1812
    radiusSecret = "secret"
    quota = {"organization": -1, "user": -1, "application": -1, "provider": -1}
    logConfig = {"filename": "logs/casdoor.log", "maxdays":99999, "perm":"0770"}
    initDataFile = "./init_data.json"
    frontendBaseDir = "../casdoor"
  token_jwt_key.pem: |
    -----BEGIN CERTIFICATE-----
    MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
    bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTI0MDgwODEwMTY0MloXDTQ0
    MDgwODEwMTY0MlowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
    bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDWJfVWKb7k7jjz
    MPAp9WoWtb1yegGEtIiug/LnMfLS2xgJlnZY4rCmJQYjwFsKyEEuKddTlyR+z4Va
    qOFnFVDQeyZWXmHFh1OCjcNujufJhc4k7MKn4TbHWAqA7VzUPtjYcFpvBTNRQvI8
    TbVeCU8iaGEhKAa2BeRUo6NCbVnHvD02tABfQOBBsxK+P2zrMpiEaZEJe0IoLhig
    iCzm7Ee5kj2XcB0R3o6BI5GrOWcijTP7MxXqdiLmt4TKJnxmyAFhW/8UQEd0XofT
    K4UIAFX3zqBYu6jWdh4efyrmv2Op7MdbX9eBK7udPPvJgcZa56LMgBZqapa7y6zZ
    wGHXnUOLZd8TJsnZumAvYzCRRhWDmwgvzr8BkMKSayET4mcz69Xxe4cgqYVXZzN0
    CDaznU0yVBo0llz8Qvua7fLYGyHZaBgZfBBeOhB9L/Pi/F5bRBFav2uXHlXoY03M
    e90AlP6ys87nzdxHmGz8YlsP+nw2hCfQUh/tLOM+gDJNzSlBKtYViBLaHnNroMJI
    GU8QNTnQTERMoULOLAz6Abo8HIN7rxq2mwKCiOqCsR9Z2xYUjVkADTEPpWMm8LbR
    xZ937qPFrRUxTApnFY98LSGN+b1tcUeEpxCesYYwoJojpc7+zzHu3U4zNILVg08i
    DNOw6PAaunFQmMxyFr4/rozV74LAAwIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
    CSqGSIb3DQEBCwUAA4ICAQBl5CI0+wd/hh3lEapqywrs3b9vNU5cB9tN/1f2iSsb
    AbK1WgMq2fPFRwPS5Z+PykOHBInpP9KD6b2Xtk83CDkZ87xxtkYIrDTxys6JtDpq
    OfmZOP5JkS0ZICnztGldmd6kKTKPUpYxSpsfcm/pV8MV2NN4T4p773tvfeYJd2PG
    uNKWQ+6rPhHd5LvlzqPfwo/P8y24fQh/7SO26MqicKi+FpgNXe/C49uZ//lHXucT
    9+MYghCSTBrVDxi/yo1zTx3y8ZZKbqP/eCVGwCJ/X+5DIxuDD2ygdDMXWcSbhHl8
    7eNbeXVopnYMB8SQrE5vW6U2h4IBPKrUR0CgwYAIfgoT2m8uOE+Mxse/ZT2reIZf
    R27WbcIx67bC+bYwT0DL4p2F5+Bjuf1jrrV02zaCYYfXl1Mp39k4r59hY7PlJq+U
    wQYwMGZ5GFSL2Vbnn7ToHf60SEGCHPGxm3ZNfmfPOr2U2lF/9F1Q3HGLr7q/9pMV
    eKQJzbjmKJ+IHOo01ufybMTKkVzBL7+pbGDn3gjSuP0AsDm8kqVIP1hYuE0fNWlQ
    VWkhZ5qoAHvp5WfnFy0ClMMYKCnwTn4DF6W7ghrlS9qtbkDSooEWUIB1e1WbH7Xz
    LbXarK0um/IB9G3lOOOdjhp+kWNFIx/9Fo729ZGkbzBO+6QM0T3fGFhy8Ex1YLeC
    mA==
    -----END CERTIFICATE-----