{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.gitea (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
data:
  GITEA_DOMAIN: {{ include "gitea.external.domain" . }}
  GITEA_ROOT_URL: {{ include "gitea.external.endpoint" . }}
  GITEA_HTTP_PORT: {{ 3001 | quote }}
  GITEA_SSH_DOMAIN: {{ include "csghub.external.domain" . }}
  {{- if eq .Values.global.ingress.service.type "NodePort" }}
  GITEA_SSH_PORT: {{ 30022 | quote }}
  {{- else }}
  GITEA_SSH_PORT:  {{ 22 | quote }}
  {{- end  }}
  GITEA_SSH_LISTEN_PORT:  {{ 22 | quote }}
  GITEA_APP_URL:  {{ include "gitea.external.endpoint" .  }}
  GITEA_APP_NAME: "CSGHub-Git: Git with a cup of tea"
  {{- if $conf.smtp.enabled }}
  GITEA_SMTP_ENABLED: {{ $conf.smtp.enabled | quote }}
  {{- with $conf.smtp }}
  GITEA_SMTP_FROM: {{ .from }}
  GITEA_SMTP_HOST: {{ .host }}
  GITEA_SMTP_PORT: {{ .port | quote }}
  GITEA_SMTP_USER: {{ .user }}
  GITEA_SMTP_PASSWORD: {{ .password }}
  {{- end }}
  {{- end }}
  GITEA_DATABASE_TYPE: "postgres"
  {{- if .Values.global.postgresql.enabled }}
  GITEA_DATABASE_HOST: {{ include "postgresql.internal.domain" . }}
  GITEA_DATABASE_PORT_NUMBER: {{ include "postgresql.internal.port" . | quote }}
  GITEA_DATABASE_NAME: "csghub_git"
  GITEA_DATABASE_USERNAME: "csghub_git"
  {{- else }}
  {{- with $conf.postgresql }}
  GITEA_DATABASE_HOST: {{ .host }}
  GITEA_DATABASE_PORT_NUMBER: {{ .port | quote }}
  GITEA_DATABASE_NAME: {{ .database }}
  GITEA_DATABASE_USERNAME: {{ .user }}
  GITEA_DATABASE_PASSWORD: {{ .password }}
  {{- end }}
  GITEA_DATABASE_SSL_MODE: "disable"
  GITEA_DATABASE_SCHEMA: "public"
  {{- end }}
  GITEA_LFS_START_SERVER: "true"
  {{- if .Values.global.minio.enabled }}
  GITEA_LFS_STORAGE_TYPE: minio
  GITEA_LFS_MINIO_ENDPOINT: {{ include "minio.internal.endpoint" . | trimPrefix "http://" }}
  GITEA_LFS_MINIO_BUCKET: "csghub-git"
  GITEA_LFS_MINIO_LOCATION: "cn-north-1"
  GITEA_LFS_MINIO_USE_SSL: "false"
  {{- else }}
  {{- with $conf.objectStore }}
  GITEA_LFS_STORAGE_TYPE: {{ .type }}
  GITEA_LFS_MINIO_ACCESS_KEY_ID: {{ .accessKey }}
  GITEA_LFS_MINIO_SECRET_ACCESS_KEY: {{ .accessSecret }}
  GITEA_LFS_MINIO_ENDPOINT: {{ .endpoint }}
  GITEA_LFS_MINIO_BUCKET: {{ .bucketName }}
  GITEA_LFS_MINIO_LOCATION: {{ .region }}
  GITEA_LFS_MINIO_USE_SSL: {{ .ssl }}
  {{- end }}
  {{- end }}
  GITEA_SERVICE_DEFAULT_ALLOW_CREATE_ORGANIZATION: "true"
  GITEA_SERVICE_DISABLE_REGISTRATION: "false"
  GITEA_LOG_MODE: file
  GITEA_LOG_ROOT_PATH: "/opt/bitnami/gitea/logs"
  BITNAMI_DEBUG: "true"
{{- end }}