{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.registry (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
spec:
  type: {{ $conf.service.type }}
  ports:
    {{- if eq $conf.service.type "NodePort" }}
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: registry
      nodePort: {{ $conf.service.port }}
    {{- else }}
    - port: {{ $conf.service.port }}
      targetPort: 5000
      protocol: TCP
      name: registry
    {{- end }}
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
{{- end }}