{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.proxy }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.cm" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  STARHUB_SERVER_SPACE_SESSION_SECRET_KEY: {{ sha256sum .Release.Name | trunc 32 | quote }} # c8f771f2a178089b99172cbbd7e3b01d
  STARHUB_DATABASE_TIMEZONE: {{ include "postgresql.timezone" . | quote }}
  STARHUB_SERVER_GITSERVER_HOST: {{ include "gitea.endpoint" . | quote }}
  STARHUB_SERVER_GITSERVER_URL: {{ include "gitea.root.url" . | quote }}
  STARHUB_SERVER_GITSERVER_WEBHOOK_URL: {{ include "server.callback.url" . | quote }}
  STARHUB_SERVER_INTERNAL_ROOT_DOMAIN: {{ include "builder.internal.domain" . | quote }}
