{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.builder }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "names.svc.hl" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ $merged.service.port }}
      targetPort: 8080
      protocol: TCP
      name: {{ include "common.names.name" . }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "names.svc.docker" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2375
      targetPort: 2375
      protocol: TCP
      name: {{ include "common.names.name" . }}-docker
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}