{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.builder }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.cm" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- if eq "true" (include "redis.enabled" .) }}
  REDIS_ENDPOINT: {{ include "redis.endpoint" . }}
  {{- else }}
  REDIS_ENDPOINT: {{ printf "%s:%s" $merged.redis.host $merged.redis.port }}
  REDIS_PASSWD: {{ $merged.redis.password }}
  {{- end }}
  SPACE_DATA_PATH: "/opt/data"
  DOCKER_TLS_CERTDIR: ""
  {{- if eq "true" (include "registry.enabled" .) }}
  REGISTRY_ADDRESS: {{ include "registry.endpoint" . }}
  REGISTRY_NAMESPACE: {{ include "registry.namespace" . }}
  {{- else }}
  REGISTRY_ADDRESS: {{ $merged.registry.repository }}
  REGISTRY_NAMESPACE: {{ $merged.registry.namespace }}
  REGISTRY_USERNAME: {{ $merged.registry.username }}
  REGISTRY_PASSWORD: {{ $merged.registry.password }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.docker.cm" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  daemon.json: |
    {
      "insecure-registries": ["{{ include "registry.endpoint" . }}"],
      "registry-mirrors": ["https://registry.cn-hangzhou.aliyuncs.com"]
    }