{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.minio }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
{{- if $merged.enabled }}
{{- $secret := (include "names.secret" .) -}}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secret).data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "names.secret" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- with $merged.authentication }}
  {{- $username := .username | b64enc }}
  {{- $password := default (include "common.initPass" .) .password | b64enc }}
  {{- if $secretData }}
  {{- $username = index $secretData "MINIO_ROOT_USER" }}
  {{- $password = index $secretData "MINIO_ROOT_PASSWORD" }}
  {{- end }}
  {{- if $username }}
  MINIO_ROOT_USER: {{ $username }}
  {{- else }}
  {{ fail "A Valid auth.username entry is required!" }}
  {{- end }}
  {{- if $password }}
  MINIO_ROOT_PASSWORD: {{ $password }}
  {{- else }}
  {{ fail "A Valid auth.password entry is required!" }}
  {{- end }}
  {{- end }}
{{- end }}