{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.postgresql }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
{{- if $merged.enabled }}
{{- $secret := (include "names.secret" .) -}}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secret).data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "names.secret" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $userList := $merged.databases }}
  {{- range $username := (append $userList "postgres") }}
  {{- $database := printf "%s_production" $username -}}
  {{- $password := include "postgresql.initPass" $database | b64enc }}
  {{- if $secretData }}
  {{- $password = index $secretData $username }}
  {{- end }}
  {{- if and $username $password }}
  {{ $username }}: {{ $password }}
  {{- end }}
  {{- end }}
{{- end }}