{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.minio (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
data:
  initialize.sh: |
    #!/bin/bash
    set -e
    alias="myMinio"
    {{ printf "mc alias set $alias %s $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD" ( printf "http://%s:%s" (include "common.names.custom" .) ($conf.service.port | toString) ) }}
    {{- if $conf.region }}
    mc admin config set "$alias" region name={{ $conf.region }}
    mc admin service restart "$alias" --quiet
    {{- end }}
    set +e
    {{- range $bucket := $conf.buckets }}
    mc ls $alias/{{ $bucket }} &>/dev/null
    if [[ $? -eq 0 ]]; then
      echo "Bucket \`$alias/{{ $bucket }}\` already exists."
    else
      {{- if and $conf.region $bucket }}
        {{- printf "mc mb --region=%s $alias/%s" $conf.region $bucket | nindent 6 }}
      {{- else }}
        {{- printf "mc mb $alias/%s" $bucket | nindent 6 }}
      {{- end }}
    fi
    {{- end }}
    {{- end }}