{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.minio }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
{{- if $merged.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "names.job" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: {{ include "names.job" . }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with (default .Values.global.imagePullSecrets $merged.image.pullSecret) }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-service
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/curlimages/curl:latest
          command: [ 'sh', '-c', 'until curl -s {{ include "minio.endpoint" . }}/minio/health/live; do echo "Waiting for service minio ready to connect"; sleep 3; done; sleep 5' ]
          imagePullPolicy: {{ default "IfNotPresent" $merged.client.pullPolicy }}
      containers:
        - name: minio-client
          image: {{ $merged.client.repository }}:{{ $merged.client.tag}}
          imagePullPolicy: {{ $merged.client.pullPolicy }}
{{/*          command: ["sleep", "3600"]*/}}
          command: ["/bin/bash", "/data/initialize.sh"]
          envFrom:
            - secretRef:
                name: {{ include "names.secret" . }}
          volumeMounts:
            - name: initialize
              mountPath: /data
      volumes:
        - name: initialize
          configMap:
            name: {{ include "names.cm.init" . }}
{{- end }}
