{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.registry }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
{{- if $merged.enabled }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "names.sts" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with $merged.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  serviceName: {{ include "names.svc" . }}
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/registry-configmaps.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/registry-secrets.yaml") . | sha256sum }}
        {{- with $merged.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with (default .Values.global.imagePullSecrets $merged.image.pullSecret) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $merged.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      {{- if $merged.serviceAccount.create }}
      serviceAccountName: {{ include "names.sa" . }}
      automountServiceAccountToken: {{ $merged.serviceAccount.automount }}
      {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: {{ $merged.image.repository }}:{{ $merged.image.tag }}
          imagePullPolicy: {{ $merged.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: {{ include "common.names.name" . }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "names.cm" . }}
          env:
          {{- if $merged.ingress.tls.enabled }}
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/opt/certs/x509/tls.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/opt/certs/x509/tls.key"
          {{- end }}
          {{- with $merged.environments }}
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml $merged.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            {{- toYaml $merged.podSecurityContext | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
            - name: basic-auth
              mountPath: /auth
              readOnly: false
            {{- if $merged.ingress.tls.enabled }}
            - name: registry-tls-certs
              mountPath: /opt/certs/x509
            {{- end }}
      volumes:
        - name: basic-auth
          secret:
            secretName: {{ include "names.secret" . }}
        {{- if $merged.ingress.tls.enabled }}
        - name: registry-tls-certs
          secret:
            {{- if $merged.ingress.tls.autoGenerate }}
            secretName: {{ include "names.secret.tls" . }}
            {{- else }}
            secretName: {{ $merged.ingress.tls.secretName }}
            {{- end }}
        {{- end }}
      {{- with $merged.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $merged.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $merged.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        namespace: {{ .Release.Namespace | quote }}
        labels:
          {{- include "common.labels.standard" . | nindent 10 }}
        annotations:
          "helm.sh/resource-policy": keep
      spec:
        accessModes: {{ $merged.persistence.accessMode }}
        {{- if $merged.persistence.storageClass }}
        storageClassName: {{ $merged.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ $merged.persistence.size }}
{{- end }}