{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.minio }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
{{- if $merged.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "names.init.cm" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  initialize.sh: |
    #!/bin/bash
    alias="myMinio"
    {{ printf "mc alias set $alias %s $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD" ( include "minio.endpoint" . ) }}
    {{- if not $merged.region }}
    mc admin config set "$alias" region name={{ $merged.region }}
    mc admin service restart "$alias"
    {{- end }}
    {{- range $bucket := $merged.buckets }}
    mc ls $alias/{{ $bucket }} 2>/dev/null
    if [[ $? -eq 0 ]]; then
      echo "{{ $bucket }} already exists."
    else
      {{- if and (include "minio.region" $) $bucket }}
        {{- printf "mc mb --region=%s $alias/%s" $merged.region $bucket | nindent 6 }}
      {{- else }}
        {{- printf "mc mb $alias/%s" $bucket | nindent 6 }}
      {{- end }}
    fi
    {{- end }}
    {{- end }}