{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $namespace := include "runner.namespace" . }}
{{- $exists := (lookup "v1" "Namespace" "" $namespace) }}
{{- if not $exists -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
{{- end }}