{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.runner }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "names.deploy" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with $merged.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ $merged.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: 10
  template:
    metadata:
      annotations:
        {{- with $merged.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - {{ include "coredns.dns.self" . }}
        searches:
          - {{ .Release.Namespace }}.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
      {{- with (default .Values.global.imagePullSecrets $merged.image.pullSecret) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $merged.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      {{- if $merged.serviceAccount.create }}
      serviceAccountName: {{ include "names.sa" . }}
      automountServiceAccountToken: {{ $merged.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-postgresql
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/postgres:latest
          imagePullPolicy: {{ $merged.image.pullPolicy }}
          command: [ 'sh', '-c', 'until pg_isready -h {{ include "postgresql.hybrid.host" . }} -p {{ include "postgresql.hybrid.port" . }} -U {{ include "postgresql.hybrid.user" . }} ; do echo "Waiting for PostgreSQL"; sleep 3; done; sleep 3' ]
          env:
            - name: PGPASSWORD
              {{- if eq "true" (include "postgresql.enabled" .)}}
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secret" . }}
                  key: csghub_server
              {{- else }}
              value: {{ .Values.global.server.postgresql.password }}
              {{- end }}
        - name: wait-for-server
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/busybox:latest
          imagePullPolicy: {{ $merged.image.pullPolicy }}
          command: [ '/bin/sh', '-c', 'until nc -z {{ include "server.host" . }} {{ include "server.port" . }}; do echo "Waiting for server ready"; sleep 2; done; sleep 3' ]
      containers:
        - name: {{ include "common.names.name" . }}
          image: {{ $merged.image.repository }}:{{ $merged.image.tag }}
          imagePullPolicy: {{ $merged.image.pullPolicy }}
          command:
            - "/starhub-bin/starhub"
            - "deploy"
            - "runner"
          ports:
            - containerPort: 8082
              name: {{ include "common.names.name" . }}
              protocol: TCP
          env:
            - name: STARHUB_SERVER_INTERNAL_ROOT_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "server.cm" . }}
                  key: STARHUB_SERVER_INTERNAL_ROOT_DOMAIN
            - name: STARHUB_SERVER_DOCKER_REG_BASE
              value: {{ include "registry.repository" . }}
            - name: STARHUB_SERVER_DOCKER_IMAGE_PULL_SECRET
              value: {{ include "registry.secret.docker" . }}
            {{- if eq "true" (include "postgresql.enabled" .) }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secret" . }}
                  key: csghub_server
            - name: STARHUB_DATABASE_DSN
              value: "postgresql://csghub_server:$(POSTGRES_PASSWORD)@{{ include "postgresql.host" . }}:{{ include "postgresql.port" . }}/csghub_server_production?sslmode=disable"
            - name: STARHUB_DATABASE_TIMEZONE
              value: {{ include "postgresql.timezone" . }}
            {{- else }}
            - name: STARHUB_DATABASE_DSN
              value: {{ include "server.postgresql.dsn" . }}
            - name: STARHUB_DATABASE_TIMEZONE
              value: {{ $merged.postgresql.timezone }}
            {{- end }}
            {{- with $merged.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml $merged.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
            {{- toYaml $merged.podSecurityContext | nindent 12 }}
          volumeMounts:
            - name: kube-config
              mountPath: /root/.kube
              readOnly: true
            - name: docker-daemon
              mountPath: /etc/docker
              readOnly: true
            - name: docker-config
              mountPath: /root/.docker
              readOnly: true
      volumes:
        - name: kube-config
          secret:
            secretName: {{ include "kube.configs" . }}
        - name: docker-daemon
          configMap:
            name: {{ include "builder.cm.docker" . }}
        - name: docker-config
          secret:
            secretName: {{ include "registry.secret.docker" . }}
            items:
              - key: .dockerconfigjson
                path: config.json
      {{- with $merged.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $merged.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $merged.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}