# Default values for Redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
## Enable or disable the Redis component.
enabled: true

## Number of Redis replicas to deploy.
replicas: 1

image:
  ## The repository of the Redis image.
  repository: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/redis
  ## The tag of the Redis image.
  tag: 7.2.5
  ## The pull policy for the Redis image.
  pullPolicy: "IfNotPresent"
  ## Image pull secrets for accessing private Docker registries.
  pullSecret: [ ]

service:
  ## The type of service to expose Redis.
  type: ClusterIP
  ## The port on which the Redis service is exposed.
  port: 6379

## Password for Redis authentication. Leave it as an empty string if no password is required.
authentication:
  password: "test"

persistence:
  ## Enable or disable persistence using Persistent Volume Claims.
  enabled: true
  ## The storage class to use for persistence. Use an empty string to use the default storage class.
  storageClass: ""
  ## The access mode of the storage. ReadWriteOnce means the volume can be mounted as read-write by a single node.
  accessMode:
    - ReadWriteOnce
  ## The size of the persistent volume.
  size: 1Gi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Defined environment
environments: {}

annotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
