{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.postgresql (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: {{ template "common.capabilities.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ $conf.service.port }}
      from:
        - podSelector:
            matchLabels:
              {{- include "common.labels.selector.netpol" . | nindent 14 }}
  egress:
    - {}
{{- end }}
