# Default values for Portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: true

## Number of portal replicas to deploy for handling incoming traffic and ensuring high availability.
replicas: 1

image:
  ## The repository where the portal image is stored.
  repository: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_portal
  ## The specific version tag of the portal image to use.
  tag: v0.5.0
  ## The pull policy for the portal image, specifying when to pull the image from the repository.
  pullPolicy: "IfNotPresent"
  ## Secrets used to pull images from a private repository. Leave empty if not required.
  pullSecret: [ ]

# Open external listening ports
service:
  type: ClusterIP
  port: 3000

## Configuration for the PostgreSQL database connection.
postgresql:
  ## The hostname or IP address of the PostgreSQL server.
  host: ""
  ## The port on which the PostgreSQL server is listening.
  port: 5432
  ## The username for authenticating with the PostgreSQL database.
  user: ""
  ## The password for authenticating with the PostgreSQL database.
  password: ""
  ## The name of the database to use within the PostgreSQL server.
  database: ""

## Configuration for S3 storage connection
## Portal can use S3 (or compatible) storage for repository data. Configure your S3 connection details here.
## Uncomment and fill in your S3 storage details.
objectStorage:
  type: ""
  endpoint: ""
  accessKey: ""
  accessSecret: ""
  bucket: ""
  region: ""
  pathStyle: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Defined environment
environments: {}

annotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
