{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $global := .Values.global.server }}
{{- $local := omit .Values "global" "exports" }}
{{- $merged := merge $global $local }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "names.deploy" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  {{- with $merged.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ $merged.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: 10
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/server-configmaps.yaml") . | sha256sum }}
        {{- with $merged.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
    spec:
      {{- with (default .Values.global.imagePullSecrets $merged.image.pullSecret) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $merged.securityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      {{- if $merged.serviceAccount.create }}
      serviceAccountName: {{ include "names.sa" . }}
      automountServiceAccountToken: {{ $merged.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-postgresql
          image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/postgres:latest
          imagePullPolicy: {{ $merged.image.pullPolicy }}
          command: [ 'sh', '-c', 'until pg_isready -h {{ include "postgresql.hybrid.host" . }} -p {{ include "postgresql.hybrid.port" . }} -U {{ include "postgresql.hybrid.user" . }} ; do echo "Waiting for PostgreSQL"; sleep 3; done; sleep 3' ]
          env:
            - name: PGPASSWORD
              {{- if eq "true" (include "postgresql.enabled" .)}}
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secret" . }}
                  key: postgres
              {{- else }}
              value: {{ .Values.global.server.postgresql.password }}
              {{- end }}
      containers:
        - name: {{ include "common.names.name" . }}
          image: {{ $merged.image.repository }}:{{ $merged.image.tag }}
          imagePullPolicy: {{ $merged.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: {{ include "common.names.name" . }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "names.cm" . }}
            - secretRef:
                name: {{ include "nats.secret" . }}
          env:
            - name: GITEA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "gitea.secret" . }}
                  key: GITEA_ADMIN_USER
            - name: GITEA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gitea.secret" . }}
                  key: GITEA_ADMIN_PASSWORD
            - name: STARHUB_SERVER_GITSERVER_USERNAME
              value: "$(GITEA_USERNAME)"
            - name: STARHUB_SERVER_GITSERVER_PASSWORD
              value: "$(GITEA_PASSWORD)"
            - name: STARHUB_SERVER_MIRRORSERVER_USERNAME
              value: "$(GITEA_USERNAME)"
            - name: STARHUB_SERVER_MIRRORSERVER_PASSWORD
              value: "$(GITEA_PASSWORD)"
            - name: STARHUB_SERVER_MIRRORSERVER_HOST
              value: "$(STARHUB_SERVER_GITSERVER_URL)"
            - name: OPENCSG_ACCOUNTING_NATS_URL
              value: "nats://$(NATS_USERNAME):$(NATS_PASSWORD)@{{ include "nats.host" . }}:{{ include "nats.ports.api" . }}"
            - name: STARHUB_SERVER_CASDOOR_CERTIFICATE
              value: "/starhub-bin/casdoor/tls.crt"
            {{- if eq "true" (include "postgresql.enabled" .) }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secret" . }}
                  key: csghub_server
            - name: STARHUB_DATABASE_DSN
              value: "postgresql://csghub_server:$(POSTGRES_PASSWORD)@{{ include "postgresql.host" . }}:{{ include "postgresql.port" . }}/csghub_server_production?sslmode=disable"
            {{- else }}
            - name: STARHUB_DATABASE_DSN
              value: {{ include "server.postgresql.dsn" . }}
            {{- end }}
            {{- if eq "true" (include "minio.enabled" .) }}
            - name: STARHUB_SERVER_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secret" . }}
                  key: MINIO_ROOT_USER
            - name: STARHUB_SERVER_S3_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.secret" . }}
                  key: MINIO_ROOT_PASSWORD
            {{- end }}
            {{- with $merged.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml $merged.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            {{- toYaml $merged.podSecurityContext | nindent 12 }}
          volumeMounts:
            - name: jwt-token-crt
              mountPath: /starhub-bin/casdoor
      volumes:
        - name: jwt-token-crt
          secret:
            secretName: {{ include "casdoor.secret" . }}
      {{- with $merged.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $merged.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $merged.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}